server:
  port: 7000
spring:
  application:
    name: zuul-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    enabled: true

############ zuul ##########
zuul:
  host:
    # 代理普通的http请求超时时长
    connect-timeout-millis: 2000
    # socket超时
    socket-timeout-millis: 1000
    # http连接池大小
    max-total-connections: 200
    # 每个host最大连接数
    max-per-route-connections: 20
    ##信号量模式
  ribbon-isolation-strategy: semaphore
  ##最大信号量
  semaphore:
    max-semaphores: 100
    ##路由代理
  routes:
    route1:
      path: /kane/**
      url: http://localhost:8081
    route2:
      path: /tony/**
      serviceId: hello-service

    user-token:
      path: /token/byPhone
      serviceId: user-demo

stduy:
  zuul:
    token-filter:
      noAuthenticationRoutes: user-token
